version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Symfony_CRM
      MYSQL_USER: rooter
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - database-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8080:80
    environment:
      MYSQL_USER: rooter
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database-data:
###< doctrine/doctrine-bundle ###
